spring:
  application:
    name: soj-backend
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss # 日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 日期格式
    time-zone: GMT+8 # 时区
    serialization:
      write-dates-as-timestamps: false # 是否将日期转换为时间戳
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
  session:
    store-type: redis
    timeout: 2592000 # 30天过期

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
  openapi:
    title: 在线判题系统接口文档
    description: "在线判题系统接口文档"
    email: 1796475983@qq.com
    concat: Shiro
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 在线判题系统
        api-rule: package
        api-rule-resources:
          - com.shiro.soj.controller

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
      id-type: assign_id # 主键类型 assign_id:雪花算法 (限制爬虫)

# 阿里云OSS配置
oss:
  bucket-name: ${aliOSS.bucket-name}
alibaba:
  cloud:
    access-key: ${aliOSS.access-key-id}
    secret-key: ${aliOSS.access-key-secret}
    oss:
      endpoint: ${aliOSS.endpoint}

# 代码沙箱配置
codeSendBox:
  type: remote